# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values
#do not exceed four million, find the sum of the even-valued terms.

number=0
firstnumber=0
secondnumber=1
our_cool_sum=0
while number < 4000000:
    #print(number)
    number=firstnumber + secondnumber
    firstnumber = secondnumber
    secondnumber=number
    if not number % 2:
        our_cool_sum += number
    print(number)
print("Our sum is %s" % our_cool_sum)
